variables:
  OMPI_VER: '3.1.6'
  CMAKE_VER: '3.15.4'
  HDF5_VER: '1.10.6'
  UCX_VER: '1.8.1'

# Is performed before the scripts in the stages step
before_script:
    - git submodule init
    - git submodule update
    - export OMP_PROC_BIND=close
    - export OMP_PLACES=cores
    - export OMP_NUM_THREADS=1
    - export CTEST_OUTPUT_ON_FAILURE=1
    - export J=$(( $(nproc --all) / 4  + 1 )) && echo Using ${J} cores during build
    - export PATH=${PWD}/opt/cmake-${CMAKE_VER}-Linux-x86_64/bin:$PATH
    - export PATH=${PWD}/opt/openmpi-${OMPI_VER}/bin:$PATH
    - export LD_LIBRARY_PATH=${PWD}/opt/openmpi-${OMPI_VER}/lib:$LD_LIBRARY_PATH
    - export LD_LIBRARY_PATH=${PWD}/opt/ucx-${UCX_VER}/lib:$LD_LIBRARY_PATH
    - module load python3
    - killall mpi_bandwidth

cache: &global_cache
  key: global-5
  paths:
    - opt/
  policy: pull-push

stages:
  - prep-cuda
  - test
  - prep-icc
  - regression


prep-cuda:
  stage: prep-cuda
  tags:
    - gpu
    - springdale7
  script:
    - module load cudatoolkit/10.2 gcc/7.3.0
    - if [ ! -d opt/ucx-${UCX_VER} ]; then
      mkdir -p tmp;
      cd tmp;
      wget https://github.com/openucx/ucx/archive/v${UCX_VER}.tar.gz;
      tar xzf v${UCX_VER}.tar.gz;
      cd ucx-${UCX_VER};
      ./autogen.sh;
      mkdir build;
      cd build;
      ../contrib/configure-release --prefix=${CI_PROJECT_DIR}/opt/ucx-${UCX_VER} --enable-mt --with-cuda=/usr/local/cuda-10.2;
      make -j16;
      make install;
      cd ../../../;
      fi
    - if [ ! -d opt/openmpi-${OMPI_VER} ]; then
      mkdir -p tmp;
      cd tmp;
      wget https://download.open-mpi.org/release/open-mpi/v3.1/openmpi-${OMPI_VER}.tar.bz2;
      tar xjf openmpi-${OMPI_VER}.tar.bz2;
      cd openmpi-${OMPI_VER};
      ./configure --prefix=${CI_PROJECT_DIR}/opt/openmpi-${OMPI_VER} --enable-mpi-fortran=none --enable-mpi-cxx --with-cuda --with-ucx=${CI_PROJECT_DIR}/opt/ucx-${UCX_VER};
      make -j16;
      make install;
      cd ../..;
      fi
    - if [ ! -d opt/hdf5-${HDF5_VER}/gcc ]; then
      mkdir -p tmp;
      cd tmp;
      wget https://hdf-wordpress-1.s3.amazonaws.com/wp-content/uploads/manual/HDF5/HDF5_1_10_6/source/hdf5-${HDF5_VER}.tar.bz2;
      tar xjf hdf5-${HDF5_VER}.tar.bz2;
      cd hdf5-${HDF5_VER};
      CC=gcc ./configure --prefix=${CI_PROJECT_DIR}/opt/hdf5-${HDF5_VER}/gcc/serial && make -j16 && make install && make clean;
      CC=mpicc ./configure --prefix=${CI_PROJECT_DIR}/opt/hdf5-${HDF5_VER}/gcc/parallel --enable-parallel && make -j16 && make install && make clean;
      cd ../..;
      fi
    - if [ ! -d opt/cmake-${CMAKE_VER}-Linux-x86_64 ]; then
      cd opt;
      wget -qO- http://www.cmake.org/files/v${CMAKE_VER:0:4}/cmake-${CMAKE_VER}-Linux-x86_64.tar.gz | tar -xz;
      cd ..;
      fi
    - python --version
    - python3 --version
    - python3 -m pip install matplotlib --user
      

prep-icc:
  stage: prep-icc
  tags:
    - gpu
    - springdale7
  script:
    - module load intel-mpi/intel-19.2.187
    - if [ ! -d opt/hdf5-${HDF5_VER}/intel ]; then
      mkdir -p tmp;
      cd tmp;
      wget https://hdf-wordpress-1.s3.amazonaws.com/wp-content/uploads/manual/HDF5/HDF5_1_10_6/source/hdf5-${HDF5_VER}.tar.bz2;
      tar xjf hdf5-${HDF5_VER}.tar.bz2;
      cd hdf5-${HDF5_VER};
      CC=icc ./configure --prefix=${CI_PROJECT_DIR}/opt/hdf5-${HDF5_VER}/intel/serial && make -j16 && make install && make clean;
      CC=mpiicc ./configure --prefix=${CI_PROJECT_DIR}/opt/hdf5-${HDF5_VER}/intel/parallel --enable-parallel && make -j16 && make install && make clean;
      cd ../..;
      fi

athenapk-cuda-test:
  tags:
    - gpu
    - springdale7
  stage: test
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull
  script:
    - module load cudatoolkit/10.2 gcc/7.3.0
    - ls -lah opt/
    - echo $PATH
    - which mpicxx
    - which cmake
    - ompi_info --all
    - lsmod
    - mkdir bw
    - cd bw
    - wget https://pgrete.de/dl/bw.tar
    - tar xvf bw.tar
    - mkdir build
    - cd build
    - export OMPI_CXX=${CI_PROJECT_DIR}/external/Kokkos/bin/nvcc_wrapper
    - cmake -DKokkos_ROOT=${CI_PROJECT_DIR}/external/Kokkos -DCMAKE_CXX_COMPILER=mpicxx -DKokkos_ENABLE_CUDA=True ..
    - make -j10
    - ldd ./mpi_bandwidth
#    - export OMPI_MCA_btl_openib_cuda_async_recv=false
#    - export OMPI_MCA_btl_openib_want_cuda_gdr=true
#    - mpirun -np 2 -mca btl_openib_allow_ib 1  -mca btl ^uct -x UCX_NET_DEVICES=mlx4_0:1 --mca mpi_common_cuda_verbose 100 --mca btl_smcuda_cuda_ipc_verbose 100 ./mpi_bandwidth --kokkos-ndevices=2
    - mpirun -np 2 ./mpi_bandwidth --kokkos-ndevices=2

athenapk-cuda:
  tags:
    - gpu
    - springdale7
  stage: regression
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull
  script:
    - module load cudatoolkit/10.2 gcc/7.3.0
    - which mpicxx
    - which cmake
    - mkdir build-cuda
    - cd build-cuda
    - cmake -DCMAKE_BUILD_TYPE=Release 
      -DKokkos_ENABLE_OPENMP=True -DKokkos_ARCH_SKX=True
      -DKokkos_ENABLE_CUDA=True -DKokkos_ARCH_VOLTA70=True
      -DCMAKE_CXX_COMPILER=${PWD}/../external/Kokkos/bin/nvcc_wrapper
      -DKokkos_ROOT=$(pwd)/../external/Kokkos
      -DHDF5_ROOT=${CI_PROJECT_DIR}/opt/hdf5-${HDF5_VER}/gcc/serial
      -DPARTHENON_DISABLE_MPI=ON
      -DPARTHENON_LINT_DEFAULT=OFF
      ../
    - make -j${J} 
    - for M in 128; do
      for N in 128 64 32; do
        ./src/athenaPK -i ../inputs/linear_wave3d.in parthenon/meshblock/nx1=$((2*N)) parthenon/meshblock/nx2=$N parthenon/meshblock/nx3=$N parthenon/mesh/nx1=$((2*M)) parthenon/mesh/nx2=$M parthenon/mesh/nx3=$M parthenon/mesh/num_threads=1 parthenon/mesh/num_streams=1 hydro/use_scratch=false hydro/scratch_level=0;
      done; done
    - for M in 128; do
      for N in 128 64 32; do
        ./src/athenaPK -i ../inputs/linear_wave3d.in parthenon/meshblock/nx1=$((2*N)) parthenon/meshblock/nx2=$N parthenon/meshblock/nx3=$N parthenon/mesh/nx1=$((2*M)) parthenon/mesh/nx2=$M parthenon/mesh/nx3=$M parthenon/mesh/num_threads=1 parthenon/mesh/num_streams=1 hydro/use_scratch=true hydro/scratch_level=1;
      done; done
    - for M in 16 32 64 128; do
      export N=$M;
        ./src/athenaPK -i ../inputs/linear_wave3d.in parthenon/meshblock/nx1=$((2*N)) parthenon/meshblock/nx2=$N parthenon/meshblock/nx3=$N parthenon/mesh/nx1=$((2*M)) parthenon/mesh/nx2=$M parthenon/mesh/nx3=$M parthenon/mesh/num_threads=1 parthenon/mesh/num_streams=1 hydro/use_scratch=false hydro/scratch_level=0;
      done
    - for M in 16 32 64 128; do
      export N=$M;
        ./src/athenaPK -i ../inputs/linear_wave3d.in parthenon/meshblock/nx1=$((2*N)) parthenon/meshblock/nx2=$N parthenon/meshblock/nx3=$N parthenon/mesh/nx1=$((2*M)) parthenon/mesh/nx2=$M parthenon/mesh/nx3=$M parthenon/mesh/num_threads=1 parthenon/mesh/num_streams=1 hydro/use_scratch=true hydro/scratch_level=1;
      done
    - export N=256
    - export M=256
    - ./src/athenaPK -i ../inputs/linear_wave3d.in parthenon/meshblock/nx1=$N parthenon/meshblock/nx2=$N parthenon/meshblock/nx3=$N parthenon/mesh/nx1=$M parthenon/mesh/nx2=$M parthenon/mesh/nx3=$M parthenon/mesh/num_threads=1 parthenon/mesh/num_streams=1 hydro/use_scratch=false hydro/scratch_level=0 parthenon/time/nlim=20
    - ./src/athenaPK -i ../inputs/linear_wave3d.in parthenon/meshblock/nx1=$N parthenon/meshblock/nx2=$N parthenon/meshblock/nx3=$N parthenon/mesh/nx1=$M parthenon/mesh/nx2=$M parthenon/mesh/nx3=$M parthenon/mesh/num_threads=1 parthenon/mesh/num_streams=1 hydro/use_scratch=true hydro/scratch_level=1 parthenon/time/nlim=20
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - build-cuda/CMakeFiles/CMakeOutput.log
      - build-cuda/linearwave-errors.dat
