variables:
  CMAKE_VER: '3.20.3'

# Is performed before the scripts in the stages step
before_script:
  - git submodule init
  - git submodule foreach git reset --hard
  - git submodule update
  - export OMP_PROC_BIND=close
  - export OMP_PLACES=cores
  - export OMP_NUM_THREADS=1
  - export CMAKE_VERSION=3.20.3
  - export CTEST_OUTPUT_ON_FAILURE=1
  - export J=4 && echo Using ${J} cores during build
  - export PATH=${PWD}/opt/cmake-${CMAKE_VER}-linux-x86_64/bin:$PATH
  - export KOKKOS_NUM_DEVICES=1
  - export CUDA_VISIBLE_DEVICES=0
# trying to use a less frequently used GPU on the node
  - module load anaconda3/2020.02
  # required as functions like "activate" are not available in subshells, see
  # see https://github.com/conda/conda/issues/7980
  - source /opt/sns/anaconda3/2020.02/etc/profile.d/conda.sh

cache: &global_cache
  key: global-2
  paths:
    - opt/
  policy: pull-push

stages:
  - prep
  - regression


prep-cuda:
  stage: prep
  tags:
    - gpu
    - springdale7
  script:
    - module load cudatoolkit/11.1 rh/devtoolset/8 openmpi/cuda-11.0/gcc/4.0.4/64 hdf5/gcc/1.10.0
    - module show openmpi/cuda-11.0/gcc/4.0.4/64
    - ls /usr/local/openmpi/cuda-11.0/4.0.4/gcc/x86_64/bin
    - env
    - which mpicxx
    - mpicxx --version
    - exit 1
    - mkdir -p opt
    - if [ ! -d opt/cmake-${CMAKE_VER}-linux-x86_64 ]; then
      cd opt;
      wget -qO- http://www.cmake.org/files/v${CMAKE_VER:0:4}/cmake-${CMAKE_VER}-linux-x86_64.tar.gz | tar -xz;
      cd ..;
      fi


cuda-regression:
  tags:
    - gpu
    - springdale7
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy (cache not changed in this stage)
    policy: pull    
  stage: regression
  script:
    - module load cudatoolkit/11.1 rh/devtoolset/8 openmpi/cuda-11.0/gcc/4.0.4/64 hdf5/gcc/1.10.0
    - mkdir build-cuda
    - cd build-cuda
    - cmake
      -DKokkos_ARCH_SKX=True
      -DKokkos_ENABLE_CUDA=True -DKokkos_ARCH_VOLTA70=True
      -DCMAKE_CXX_COMPILER=${PWD}/../external/Kokkos/bin/nvcc_wrapper
      -DPARTHENON_DISABLE_MPI=ON
      ../
    - make -j${J} athenaPK
    - nvidia-smi
    - ctest
    - mkdir ../build-cuda-mpi
    - cd ../build-cuda-mpi
    - cmake
      -DKokkos_ARCH_SKX=True
      -DKokkos_ENABLE_CUDA=True -DKokkos_ARCH_VOLTA70=True
      -DCMAKE_CXX_COMPILER=${PWD}/../external/Kokkos/bin/nvcc_wrapper
      ../
    - make -j${J} athenaPK
    - nvidia-smi
    - ctest
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - build-cuda/CMakeFiles/CMakeOutput.log
      - build-cuda/tst/regression/outputs/convergence
      - build-cuda/tst/regression/outputs/mhd_convergence
      - build-cuda/tst/regression/outputs/performance
      - build-cuda-mpi/CMakeFiles/CMakeOutput.log
      - build-cuda-mpi/tst/regression/outputs/convergence
      - build-cuda-mpi/tst/regression/outputs/mhd_convergence
      - build-cuda-mpi/tst/regression/outputs/performance
